"""add recipient_email to notifications

Revision ID: 2af1b7490dc3
Revises: bed00dac6ae5
Create Date: 2026-07-20 11:40:12.805871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af1b7490dc3'
down_revision = 'bed00dac6ae5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'recipient_email')
    # ### end Alembic commands ###
