"""initial schema

Revision ID: 3f3583fec1b0
Revises: 
Create Date: 2026-07-05 23:40:43.822953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3583fec1b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('donor_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_ref_id', sa.UUID(), nullable=False),
    sa.Column('trigger_event', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('recipients',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('household_or_capacity', sa.Integer(), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_table('shifts',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_table('staff_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True)
    op.create_table('volunteers',
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('can_drive', sa.Boolean(), nullable=False),
    sa.Column('certifications', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('volunteer_id')
    )
    op.create_table('donations',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('donation_type', sa.String(length=20), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.donor_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('route_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vehicle', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('shift_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.volunteer_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('shift_id', 'volunteer_id')
    )
    op.create_table('inventory_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('donation_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('route_stops',
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.recipient_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('stop_id'),
    sa.UniqueConstraint('route_id', 'sequence_number')
    )
    op.create_table('route_stop_items',
    sa.Column('route_stop_item_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_delivered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.item_id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['route_stops.stop_id'], ),
    sa.PrimaryKeyConstraint('route_stop_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_stop_items')
    op.drop_table('route_stops')
    op.drop_table('inventory_items')
    op.drop_table('shift_assignments')
    op.drop_table('routes')
    op.drop_table('donations')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_table('shifts')
    op.drop_table('recipients')
    op.drop_table('notifications')
    op.drop_table('donors')
    # ### end Alembic commands ###
